### PR TITLE
Don't require rubocop/rspec/language/node_pattern

### LINKED ISSUE #41: `rubocop-rsepc_rails` not compatible with `rubocop-rspec` v3
I realise that v3 of `rubocop-rsepc` has only just been released but I thought I'd raise this anyway.

`rubocop-rsepc_rails` requires `'rubocop/rspec/language/node_pattern'` which can be seen here: https://github.com/rubocop/rubocop-rspec_rails/blob/master/lib/rubocop-rspec_rails.rb#L8

However, v3 `rubocop-rsepc` has removed this file (not sure if moved, deleted or changed) and so `rubocop` crashes when requiring `rubocop-rsepc_rails`

---
Note the below commnad actually crashes but I am able to work out what it would output
```
rubocop -V
```
Output:
```
1.64.1 (using Parser 3.3.2.0, rubocop-ast 1.31.3, running on ruby 3.3.1) [x86_64-darwin22]
  - rubocop-capybara 2.20.0
  - rubocop-factory_bot 2.25.1
  - rubocop-rails 2.25.0
  - rubocop-rspec 3.0.0
  - rubocop-rspec_rails 2.28.3
```

### PR DESCRIPTION
**Pull request by bquorning**
The node_pattern file has been removed from rubocop-rspec, and we should no longer require it.

Also, the `RSpec/FilePath` has been split and `RSpec/SpecFilePathFormat` can be configured to work instead.

Fixes #41.

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [ ] Added tests.
- [ ] Updated documentation.
- [ ] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: Gemfile [hunk 1]
```diff
@@ -15,7 +15,7 @@ gem 'simplecov', '>= 0.19'
 gem 'yard'
 
 # TODO: Move to gemspec when RuboCop RSpec v3 is released.
-gem 'rubocop-rspec', '~> 2.27'
+gem 'rubocop-rspec', github: 'rubocop/rubocop-rspec', ref: '1a8e9cb8b044983c94d'
```
Comment (bquorning) [inline Gemfile:18]: We cannot merge before there is a new release of rubocop-rspec.

File: lib/rubocop-rspec_rails.rb [hunk 2]
```diff
@@ -4,9 +4,6 @@
 require 'yaml'
 
 require 'rubocop'
-
-require 'rubocop/rspec/language/node_pattern'
```
Comment (pirj) [inline lib/rubocop-rspec_rails.rb:8]: We can merge this PR because we don’t need the Language::NodePattern, and we can rely on both rubocop-rspec that has it or has not, no difference. Or am I missing something?

Comment (bquorning) [reply lib/rubocop-rspec_rails.rb:8]: If I revert the change to Gemfile (and keep `gem 'rubocop-rspec', '~> 2.27'`), CI starts failing with this stacktrace:
```
TypeError: wrong argument type Class (expected Module) (TypeError)

      extend NodePattern
             ^^^^^^^^^^^
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/vendor/bundle/ruby/3.2.0/gems/rubocop-rspec-2.29.2/lib/rubocop/rspec/language.rb:16:in `extend'
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/vendor/bundle/ruby/3.2.0/gems/rubocop-rspec-2.29.2/lib/rubocop/rspec/language.rb:16:in `<module:Language>'
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/vendor/bundle/ruby/3.2.0/gems/rubocop-rspec-2.29.2/lib/rubocop/rspec/language.rb:14:in `<module:RSpec>'
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/vendor/bundle/ruby/3.2.0/gems/rubocop-rspec-2.29.2/lib/rubocop/rspec/language.rb:4:in `<module:RuboCop>'
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/vendor/bundle/ruby/3.2.0/gems/rubocop-rspec-2.29.2/lib/rubocop/rspec/language.rb:3:in `<top (required)>'
<internal:/opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/lib/rubocop-rspec_rails.rb:7:in `<top (required)>'
<internal:/opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
tasks/cops_documentation.rake:4:in `<top (required)>'
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/Rakefile:19:in `load'
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/Rakefile:19:in `block in <top (required)>'
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/Rakefile:19:in `each'
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/Rakefile:19:in `<top (required)>'
/home/runner/work/rubocop-rspec_rails/rubocop-rspec_rails/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.2.4/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.2.4/x64/bin/bundle:25:in `<main>'
```

Example run: https://github.com/rubocop/rubocop-rspec_rails/actions/runs/9161367523/job/25186054266

**Review by pirj — APPROVED** [review]
Thank you!

**Review by ydah — APPROVED** [review]

File: Gemfile [hunk 3]
```diff
@@ -14,7 +14,7 @@ gem 'simplecov', '>= 0.19'
 gem 'yard'
 
 # TODO: Move to gemspec when RuboCop RSpec v3 is released.
-gem 'rubocop-rspec', '~> 2.27'
+gem 'rubocop-rspec', '>= 3.0.0.pre'
```
Comment (bquorning) [inline Gemfile:17]: @ydah Should I move this restriction into the gemspec, and then we do a prerelease of rubocop-rspec_rails too? Or should we just wait for rubocop-rspec v3.0.0 proper?

File: rubocop-rspec_rails.gemspec [hunk 4]
```diff
@@ -35,4 +35,5 @@ Gem::Specification.new do |spec|
   }
 
   spec.add_runtime_dependency 'rubocop', '~> 1.40'
+  spec.add_runtime_dependency 'rubocop-rspec', '~> 3.0.0.pre'
```
Comment (bquorning) [inline rubocop-rspec_rails.gemspec:38]: @ydah Is it ok to have this restriction in the gemspec, and then we do a prerelease of rubocop-rspec_rails? Or should we just wait for rubocop-rspec v3.0.0 proper?

Comment (pirj) [reply rubocop-rspec_rails.gemspec:38]: I think pre-pre should be fine

**Comment by bquorning** [comment]
rubocop-rspec v3.0.0 has been released, so I updated this PR accordingly. @ydah please merge at will.

**Comment by bquorning** [comment]
@ydah Is this PR ok to merge?

**Comment by ydah** [comment]
@bquorning Let's wait until this issue is resolved.Maybe a patch release will be needed, we know.
https://github.com/rubocop/rubocop-rspec/issues/1916#issuecomment-2160544092

**Comment by mjankowski** [comment]
Just saw the rubocop-rspec 3.0 release, and attempting an update. Running with these versions:

```
  * rubocop (1.64.1)
  * rubocop-ast (1.31.3)
  * rubocop-capybara (2.21.0)
  * rubocop-performance (1.21.0)
  * rubocop-rails (2.25.0)
  * rubocop-rspec (3.0.0)
  * rubocop-rspec_rails (2.29.0)
```

And pulling them in via:

```
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-capybara
```

I see error output like:

```
cannot load such file -- rubocop/rspec/language/node_pattern
/Users/mjankowski/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
/Users/mjankowski/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
/Users/mjankowski/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rubocop-rspec_rails-2.29.0/lib/rubocop-rspec_rails.rb:8:in `<top (required)>'
/Users/mjankowski/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
/Users/mjankowski/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
/Users/mjankowski/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:35:in `load'
/Users/mjankowski/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:21:in `load'
/Users/mjankowski/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'
/Users/mjankowski/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
/Users/mjankowski/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
```

I assume this is because the latest released rubocop-rspec_rails (2.29.0 for me locally) is referencing this file which has been removed from rubocop-rspec ... and the solution is probably just wait on this PR to merge and a new release of rubocop-rspec_rails to go out?

**Comment by bquorning** [comment]
Done, now with the dependency changed to
```rb
spec.add_runtime_dependency 'rubocop-rspec', '~> 3', '>= 3.0.1'
```

**Comment by bquorning** [comment]
@rubocop/rubocop-rspec Can we merge this PR too?

**Review by ydah — APPROVED** [review]
Looks good!

**Comment by bquorning** [comment]
@ydah Are you planning to release today?
